network: DemoNet10
stations:
  - code: STA1
    lat: 35.10
    lon: 109.60
    elev: 900
  - code: STA2
    lat: 35.20
    lon: 110.00
    elev: 950
  - code: STA3
    lat: 35.30
    lon: 109.80
    elev: 850
  - code: STA4
    lat: 35.40
    lon: 110.20
    elev: 1000
  - code: STA5
    lat: 35.60
    lon: 109.55
    elev: 1200
  - code: STA6
    lat: 35.55
    lon: 109.65
    elev: 1100
  - code: STA7
    lat: 34.80
    lon: 110.00
    elev: 800
  - code: STA8
    lat: 35.70
    lon: 109.30
    elev: 1050
  - code: STA9
    lat: 34.90
    lon: 110.50
    elev: 1000
  - code: STA10
    lat: 35.65
    lon: 109.95
    elev: 980

area:
  lat: [24.0, 46.0]
  lon: [99.0, 122.0]
  depth_km: 5
  step: 0.2

snr: 2
n_req: 2

attenuation:
  logA0: -1.3
  gamma: 1.0
  kappa: 0.003